### ISSUE TITLE
Bootstrap & jquery js integration problem

### ISSUE THREAD

**Issue by weiss-d** [HabedyOmid/Gulp-Masterfy-Assets#2]
Hi, Omid! Continuing to test Bootstrap I tried to make a standard collapsible navigation bar, but the sandwich button didn't work when I just included app.js from dist:
`<script type="text/javascript" src="dist/js/app.js"></script>`
It also didn't work when I added jquery from CDN:
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>`
And finally it moved when I also added bootstrap js from CDN:
`<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>`

Looks like something's going wrong when app.js is being made.

**Comment by HabedyOmid** [comment]
@fablov Thanks for bringing up this issue.
Normally all vendors(bootstrap, jquery or other JS libraries) js files should be loaded from CDN for faster page speed and performance. but for better reliability you have the option to include them from vendors directory.  

The purpose of ```app.js``` to use it for any custom JS code, you dont want to include(compile) bootstrap within that file to reduce the file size. I encourage you to use ```app.js``` for only for custom, and then include all third-parties(vendors) separately.

Just updated the ```index.html``` for collapsable to work. i had small typo bug within ```gulpfile.js```  that has been fixed too.

here are the changes and updated you may need to do:
1- update the ```gulpfile.js```
2- run ```gulp clean```
3- run ```gulp vendors```
4- run ```gulp build```
5- update your ```index.html``` file by including the following before the closing ```</body>``` tag

```
<script src="dist/vendors/jquery/jquery-3.4.1.min.js"></script>
<script src="dist/vendors/bootstrap/bootstrap.bundle.min.js"></script>
<script src="assets/js/app.js"></script>
```

You should be all set.

**Comment by weiss-d** [comment]
Hi, Omid!
Looks like there is a problem still.
When I delete all folders in `/dist` and run `gulp build` it makes `css`, `img` and `js` folders, but not the `vendors` folder, which new script links in `index.html` refer to.
